spring:
  application:
    name: TravelAppBE

  datasource:
    url: jdbc:postgresql://localhost:5432/travellApp
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  data:
    mongodb:
      uri: mongodb://localhost:27017/travelapp_geo
      database: travelapp_geo
      username: travelapp_user
      password: travelapp_password
      authentication-database: travelapp_geo
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: man.mihai420@gmail.com
    password: "password(to be changed)"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: your-secret-key-must-be-at-least-256-bits-long-for-HS256-algorithm-requirement-please-change-in-production
  expiration: 86400000

server:
  port: 8080

app:
  admin:
    email: man.mihai420@gmail.com